package com.dynatrace.diagnostics.plugins.extendedmailreport.domain;

public enum SendOnlyVariableNames {
	MESSAGE,
	RULE_DESCRIPTION,
	VIOLATION_HEADER_1,
	VIOLATION_MESSAGE_1,
	VIOLATION_HEADER_2,
	VIOLATION_MESSAGE_2,
	VIOLATION_HEADER_3,
	VIOLATION_MESSAGE_3,
	VIOLATION_HEADER_4,
	VIOLATION_MESSAGE_4,
	VIOLATION_HEADER_5,
	VIOLATION_MESSAGE_5,

}
